#!/bin/bash

# take a text, turn it into mock-Bernard / mock-Krasznahorkai. Try a js one as well?
# so e.g. eliminate full stops. de-capitalise (but proper nouns at start???). dash or comma or semi colons
# i think: keep only leading capital letter. a la mode.

fileIn="$1"
fileOut=$(echo "${fileIn%.*}.out.txt")
cp $fileIn $fileOut

# remove newlines
sed ':a;N;$!ba;s/\n//g' $fileOut


# echo -e "bkify version of $fileIn \n" > $fileOut


