#!/bin/bash

# byte12tone
# recall https://blog.robertelder.org/bash-one-liner-compose-music/

# cat /dev/urandom
    # get random #
# hexdump -v -e '/1 "%u\n"'
    # convert into 0-255
# awk '{ split("0,2,4,5,7,9,11,12",a,","); for (i = 0; i < 1; i+= 0.0001) printf("%08X\n", 100*sin(1382*exp((a[$1%8+1]/12)*log(2))*i)) }'
    # pass integers into awk sequentially
    #does lots of stuff. work on this / modify obv
# xxd -r -p 
    # back to binary
# aplay -c 2 -f S32_LE -r 16000
    # play
